name: flutter_application_9
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  http: ^1.6.0
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/image/
    - assets/images/
    

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/font/Raleway-Bold.ttf
          weight: 700
        - asset: assets/font/Raleway-Medium.ttf
          weight: 500

    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
       
